<div id="cnt-smile" class="cnt-smile" style="display: none">
    <span class="smile">😀</span>
    <span class="smile">😄</span>
    <span class="smile">😁</span>
    <span class="smile">😆</span>
    <span class="smile">😅</span>
    <span class="smile">🤣</span>
    <span class="smile">😂</span>
    <span class="smile">🙂</span>
    <span class="smile">🙃</span>
    <span class="smile">😉</span>
    <span class="smile">😊</span>
    <span class="smile">😇</span>
    <span class="smile">🥰</span>
    <span class="smile">😍</span>
    <span class="smile">🤩</span>
    <span class="smile">😘</span>
    <span class="smile">😗</span>
    <span class="smile">☺</span>
    <span class="smile">😚</span>
    <span class="smile">😙</span>
    <span class="smile">😋</span>
    <span class="smile">😛</span>
    <span class="smile">😜</span>
    <span class="smile">🤪</span>
    <span class="smile">😝</span>
    <span class="smile">🤑</span>
    <span class="smile">🤗</span>
    <span class="smile">🤭</span>
    <span class="smile">🤫</span>
    <span class="smile">🤔</span>
    <span class="smile">🤐</span>
    <span class="smile">🤨</span>
    <span class="smile">😐</span>
    <span class="smile">😑</span>
    <span class="smile">😶</span>
    <span class="smile">😏</span>
    <span class="smile">😒</span>
    <span class="smile">🙄</span>
    <span class="smile">😬</span>
    <span class="smile">🤥</span>
    <span class="smile">😌</span>
    <span class="smile">😔</span>
    <span class="smile">😪</span>
    <span class="smile">🤤</span>
    <span class="smile">😴</span>
    <span class="smile">😷</span>
    <span class="smile">🤒</span>
    <span class="smile">🤕</span>
    <span class="smile">🤢</span>
    <span class="smile">🤮</span>
    <span class="smile">🤧</span>
    <span class="smile">🥵</span>
    <span class="smile">🥶</span>
    <span class="smile">🥴</span>
    <span class="smile">😵</span>
    <span class="smile">🤯</span>
    <span class="smile">🤠</span>
    <span class="smile">🥳</span>
    <span class="smile">😎</span>
    <span class="smile">🤓</span>
    <span class="smile">🧐</span>
    <span class="smile">😕</span>
    <span class="smile">😟</span>
    <span class="smile">🙁</span>
    <span class="smile">☹</span>
    <span class="smile">😮</span>
    <span class="smile">😯</span>
    <span class="smile">😲</span>
    <span class="smile">😳 </span>
    <span class="smile">🥺 </span>
    <span class="smile">😦</span>
    <span class="smile">😧 </span>
    <span class="smile">😨 </span>
    <span class="smile">😰 </span>
    <span class="smile">😥 </span>
    <span class="smile">😢 </span>
    <span class="smile">😭 </span>
    <span class="smile">😱 </span>
    <span class="smile">😖</span>
    <span class="smile">😣 </span>
    <span class="smile">😞  </span>
    <span class="smile">😓 </span>
    <span class="smile">😩 </span>
    <span class="smile">😫 </span>
    <span class="smile">😤 </span>
    <span class="smile">😡 </span>
    <span class="smile">😠</span>
    <span class="smile">🤬 </span>
    <span class="smile">😈 </span>
    <span class="smile">👿 </span>
    <span class="smile">💀 </span>
    <span class="smile">☠ </span>
    <span class="smile">💩 </span>
    <span class="smile">🤡 </span>
    <span class="smile">👹</span>
    <span class="smile">🙈 </span>
    <span class="smile">🙉</span>
    <span class="smile">🙊</span>
</div>
